# docker-compose.yaml

version: '3'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    environment:
      - DATABASE_URL=mysql://db:3306/symfony
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
      - ./configuration/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - symfony
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony

volumes:
  db_data:
