# docker-compose.yaml

version: '3'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL="mysql://symfony:symfony@my_database:3306/jarvis?serverVersion=5.7"
    depends_on:
      - my_database
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
      - ./configuration/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - symfony
    networks:
      - symfony_network

  my_database:
    container_name: my_database
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jarvis
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    ports:
      - "3307:3306"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
